-- Add Text-to-Speech help topic
INSERT INTO "HelpTopic" (
  "id",
  "slug",
  "category",
  "titlePl",
  "titleEn",
  "titleRu",
  "contentPl",
  "contentEn",
  "contentRu",
  "searchKeywordsPl",
  "searchKeywordsEn",
  "searchKeywordsRu",
  "order",
  "isFeatured",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'settings-text-to-speech',
  'settings',
  'Odczytywanie głosowe odpowiedzi AI',
  'Text-to-Speech for AI Responses',
  'Голосовое воспроизведение ответов AI',
  E'Czat AI obsługuje funkcję odczytywania odpowiedzi głosem za pomocą technologii Web Speech API.\n\n## Funkcje\n\n**Ręczne odtwarzanie:**\n- Kliknij ikonę głośnika 🔊 przy dowolnej odpowiedzi AI, aby ją odsłuchać\n- Kliknij ponownie, aby zatrzymać odtwarzanie\n- Odtwarzanie automatycznie zatrzymuje się po zakończeniu tekstu\n\n**Automatyczne odczytywanie:**\n- Włącz opcję "Automatyczne odczytywanie" w ustawieniach głosu\n- Nowe odpowiedzi AI będą automatycznie odczytywane głosem\n- Możesz zatrzymać odtwarzanie w dowolnym momencie\n\n**Kontrola prędkości:**\n- Dostosuj szybkość mówienia od 0.5x (powoli) do 2.0x (szybko)\n- Domyślna prędkość to 1.0x (normalna)\n\n## Jak włączyć\n\n1. Kliknij ikonę głośnika w nagłówku czatu (obok ikony pomocy)\n2. Włącz opcję "Odczytywanie głosowe"\n3. Opcjonalnie włącz "Automatyczne odczytywanie nowych wiadomości"\n4. Dostosuj prędkość mówienia według preferencji\n\n## Obsługiwane języki\n\n- 🇬🇧 Angielski (en-US)\n- 🇵🇱 Polski (pl-PL)\n- 🇷🇺 Rosyjski (ru-RU)\n\nJęzyk jest automatycznie dopasowywany do wybranego języka interfejsu.\n\n## Wskazówki\n\n- Ustawienia są zapisywane lokalnie w przeglądarce\n- Funkcja wymaga przeglądarki obsługującej Web Speech API (Chrome, Edge, Safari, Firefox)\n- Jeśli nie słyszysz dźwięku, sprawdź ustawienia głośności systemu\n- Możesz kliknąć na inną wiadomość podczas odtwarzania - poprzednia zostanie zatrzymana automatycznie',
  E'AI Chat supports voice readout of responses using Web Speech API technology.\n\n## Features\n\n**Manual playback:**\n- Click the speaker icon 🔊 on any AI response to hear it read aloud\n- Click again to stop playback\n- Playback automatically stops when the text ends\n\n**Auto-speak:**\n- Enable "Auto-read new messages" in voice settings\n- New AI responses will be automatically read aloud\n- You can stop playback at any time\n\n**Speed control:**\n- Adjust speech rate from 0.5x (slow) to 2.0x (fast)\n- Default speed is 1.0x (normal)\n\n## How to enable\n\n1. Click the speaker icon in the chat header (next to the help icon)\n2. Toggle "Voice readout" on\n3. Optionally enable "Auto-read new messages"\n4. Adjust speech rate to your preference\n\n## Supported languages\n\n- 🇬🇧 English (en-US)\n- 🇵🇱 Polish (pl-PL)\n- 🇷🇺 Russian (ru-RU)\n\nLanguage is automatically matched to your selected interface language.\n\n## Tips\n\n- Settings are saved locally in your browser\n- Feature requires a browser that supports Web Speech API (Chrome, Edge, Safari, Firefox)\n- If you don''t hear audio, check your system volume settings\n- You can click on another message during playback - the previous one will stop automatically',
  E'AI чат поддерживает голосовое воспроизведение ответов с помощью технологии Web Speech API.\n\n## Функции\n\n**Ручное воспроизведение:**\n- Нажмите на иконку динамика 🔊 у любого ответа AI, чтобы прослушать его\n- Нажмите снова, чтобы остановить воспроизведение\n- Воспроизведение автоматически останавливается по окончании текста\n\n**Автоматическое воспроизведение:**\n- Включите опцию "Автоматически читать новые сообщения" в настройках голоса\n- Новые ответы AI будут автоматически озвучиваться\n- Вы можете остановить воспроизведение в любой момент\n\n**Контроль скорости:**\n- Настройте скорость речи от 0.5x (медленно) до 2.0x (быстро)\n- Скорость по умолчанию 1.0x (нормальная)\n\n## Как включить\n\n1. Нажмите на иконку динамика в заголовке чата (рядом с иконкой помощи)\n2. Включите "Голосовое воспроизведение"\n3. При желании включите "Автоматически читать новые сообщения"\n4. Настройте скорость речи по вашему предпочтению\n\n## Поддерживаемые языки\n\n- 🇬🇧 Английский (en-US)\n- 🇵🇱 Польский (pl-PL)\n- 🇷🇺 Русский (ru-RU)\n\nЯзык автоматически соответствует выбранному языку интерфейса.\n\n## Советы\n\n- Настройки сохраняются локально в браузере\n- Функция требует браузер с поддержкой Web Speech API (Chrome, Edge, Safari, Firefox)\n- Если не слышите звук, проверьте настройки громкости системы\n- Можете кликнуть на другое сообщение во время воспроизведения - предыдущее остановится автоматически',
  ARRAY['głos', 'dźwięk', 'odczytywanie', 'mówienie', 'tts', 'text-to-speech', 'audio', 'synteza mowy'],
  ARRAY['voice', 'audio', 'speech', 'read aloud', 'tts', 'text-to-speech', 'speak', 'sound'],
  ARRAY['голос', 'звук', 'речь', 'озвучивание', 'tts', 'text-to-speech', 'аудио', 'синтез речи'],
  2,
  true,
  NOW(),
  NOW()
)
ON CONFLICT ("slug") DO UPDATE SET
  "titlePl" = EXCLUDED."titlePl",
  "titleEn" = EXCLUDED."titleEn",
  "titleRu" = EXCLUDED."titleRu",
  "contentPl" = EXCLUDED."contentPl",
  "contentEn" = EXCLUDED."contentEn",
  "contentRu" = EXCLUDED."contentRu",
  "searchKeywordsPl" = EXCLUDED."searchKeywordsPl",
  "searchKeywordsEn" = EXCLUDED."searchKeywordsEn",
  "searchKeywordsRu" = EXCLUDED."searchKeywordsRu",
  "order" = EXCLUDED."order",
  "isFeatured" = EXCLUDED."isFeatured",
  "updatedAt" = NOW();
